[package]
name = "Erros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-to-ascii-art="0.1.5"
colored = "*"
rand = "*"


